### ISSUE TITLE
Opinion: Layouts used Exclusively for Page Generation Should Be in _templates with Fresh Scope

### ISSUE THREAD

**Issue by jffrydsr** [avillafiorita/jekyll-datapage_gen#106]
1. Thanks @avillafiorita for finishing up this gem into ruby gems! I wish I could hand solutions before presenting new problems but all in good time. 
2. Surprisingly, liquid can be used in template front matter to set with datafile. 
ex. 
```yaml 
- id: home # [note]: title & content keys overlap with Layout variables. 
  data: >- my lovely content. 
  layout: basic
  perma: /:id/
  prop: value
```

```md
---
layout: {{ page.layout }} 
prop: {{ page.prop }}
permalink: {{ page.perma }}
---

# {{ page.id }}
### {{ page.data }} 
``` 
3. However, I feel this means templates used for DataGen are fundamentally different than regular layouts, so why not have their own directories? This would allow for better variable scoping too because currently, page.[key], overlaps with regular Layout object (I use 'data' instead of content due to clash). 

```_templates``` would be great! Let's all work to makes this the most feature rich gem ever! The ability to author content and configs all from YAML isn't to be taken lightly.
