### ISSUE TITLE
Support for custom data mapping

### ISSUE THREAD

**Issue by mooperd** [avillafiorita/jekyll-datapage_gen#110]
Hello,

Is it possible to use custom data mapping? For example I would like to be able to control other elements - specifically the `subtitle`, and perhaps `show_sidebar` which is part of the ??front matter??. Please excuse my ignorance - I'm very new to jekyll.

Right now `subtitle: scenario` seems to be ignored

```
page_gen:
- data: skill-sprints
  template: skill-sprint
  dir: skill-sprints
  index_files: false
  name: url
  title: name
  subtitle: scenario
```

```
---
title: Title Text
subtitle: Subtitle Text
layout: category
show_sidebar: false
---
```

Thanks,

Andrew
