### ISSUE TITLE
Would it be possible to support nested collections?

### ISSUE THREAD

**Issue by Kralizek** [avillafiorita/jekyll-datapage_gen#119]
I have a case like the following one:

```yaml
customers:
  - name: Amazing Customer
    foo: bar
    projects:
       - name: P1
         bar: foo
       - name: P2
         bar: fizz
  - name: Brilliant Customer
    foo: bas
    projects:
      - name: P3
        bar: fritz
      - name: P4
        bar: fuzz
```

I would like to generate a page for each `customer` and a page for each `project`.

It would be even better if, when rendering a project, I could access the customer it belongs to. Something like `page.parent.foo`
