### ISSUE TITLE
Nested data files?

### ISSUE THREAD

**Issue by sgofferj** [avillafiorita/jekyll-datapage_gen#134]
Is it possible to use a nested data file? I have the following regions.yaml:

```yaml
- name: Finland
  url: finland
  charts:
    - handle: cape180_0mb
      name: MUCAPE 180
      description: Most unstable CAPE 180-0hPa
      min: 100
      max: 180
    - handle: cape255_0mb
      name: MUCAPE 255
      description: Most unstable CAPE 255-0hPa
      min: 100
      max: 180
- name: Nordic
  url: nordic
- name: Germany
  url: germany
- name: Europe
  url: europe
```
I can get the plugin to loop through the top level but what I am trying to achieve is one file for each item in charts where those files are in directories named by the top level URL variable. I.e.

finland/cape180_0mb
finland/cape255_0mb
finland/...
nordic/...
germany/...
europe/...
