### ISSUE TITLE
Error when layout is a markdown file

### ISSUE THREAD

**Issue by radixdiaboli** [avillafiorita/jekyll-datapage_gen#21]
If the layout file specified in _config.yml is a .md file, I get the following error:

```
$ jekyll build --trace
Configuration file: /Users/Project/tilefarm_html/_config.yml
            Source: /Users/Project/tilefarm_html
       Destination: /Users/Project/tilefarm_html/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
error. could not find template workshop.md
                    done in 0.613 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

```

I get no errors if I rename the .md file to .html (but the markdown does not get rendered by Jekyll).

Relevant field from _config.yml:

```
# Markdown config
markdown: kramdown
kramdown:
  parse_block_html: true

# Page generator https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: test
    template: workshop.md
    name: filename
    dir: /pages/workshops/
    extension: md

```
