### ISSUE TITLE
Generate .md pages to root?

### ISSUE THREAD

**Issue by mnyrop** [avillafiorita/jekyll-datapage_gen#26]
Hello, and thank you so much for your incredibly helpful plugin!

I've been trying (unsuccessfully) for a few hours to augment the plugin to generate the directory and pages to the root folder as markdown instead of pre-rendered as html within the `_site` folder. I thought this would be relatively trivial. Is there something I'm missing?

i.e., for `_config.yml`:

```
page_gen:
   - data: 'image'
     template: 'image-page'
     name: 'title'
     dir: 'collection'
     extension: 'md'
```

I need:

```
+-- _data
|   +--image.yml
+-- _includes
+-- _layouts
+-- _collection
|   +--page-example1.md
|   +--page-example2.md
|   +--...
+-- _config.yml
+-- Gemfile
```

where the front matter of each .md page is pulled from the initial `_data/image.yml`.

(This seems to be exactly what happens on `jekyll build`, except that the .md files aren't kept anywhere.) Any thoughts? Do I need to integrate the plugin to work with Jekyll collections?

Thanks!
