### ISSUE TITLE
Not working with Github pages

### ISSUE THREAD

**Issue by somecallmejosh** [avillafiorita/jekyll-datapage_gen#28]
Pages are building locally with Jekyll. Not building on Github pages for some reason. This is what my config file looks like:

```
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'contentful.spaces.links.page'
    template: 'page'
    name: 'page_slug'
    dir: ''
```

If I attempt to bundle `gem "github-pages", group: :jekyll_plugins` (even locally) the pages no longer build. Any suggestions?
