### ISSUE TITLE
Cannot generate from more than 2 sources

### ISSUE THREAD

**Issue by RandyMustache** [avillafiorita/jekyll-datapage_gen#34]
My site requires me to work from a number of YML data sources. I found your plugin incredibly useful for creating a staff directory, so I planned to extend it to some other pages where it would be useful to just generate them off the data source.

When I added a second it worked perfectly, but when I added a 3rd, they all broke. 

Any guidance on this issue would be massively appreciated. 

Example code:

```
page_gen:
  - data: 'contacts'
    template: 'profile'
    name: 'name'
    dir: 'field-support/contacts/'

page_gen:
  - data: 'cbt'
    template: 'profile'
    name: 'title'
    dir: 'CBT/'

page_gen:
  - data: 'platform-reference'
    template: 'profile'
    name: 'title'
    dir: 'platform-reference/'
```

2 of these will work, in any order. But 3 will not.
