### ISSUE TITLE
If template is found: Error: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by Sakrecoer** [avillafiorita/jekyll-datapage_gen#49]
First of all, thank you for writing this plugin, I've been looking high and low for something like this.

However i fail to put it to proper use. 

With jekyll 3.8.3 if i enter a valid layout name in `_config.yml`, jekyll gives me the aforementioned error and exits.

If i enter a bogus layout name, jekyll will complain about a missing template but run successfully, although obviously no pages are generated.

Content of _config.yml:
```
page_gen:
  - data: releases
    template: album
    name: releases.title
    dir: records
```
Content of layout in `_layouts/album.html`
```
{{ page.title }}
``` 
Content of `_data/releases.yml` 

```
- 
  archive: "https://archive.org/details/BPIST013"
  artist: tfb
  coverart: 
    art: "TFB-OTK.png"
    thumb: "TFB-OTK.png"
  description: "Enter this cybernetic opus of oblivion and computer aided overstanding, grown somewhere beyond the laws of physics.<br />From earth to your folder, we send you vibrant energy, defying the relative time of life. We wanted to hand you the key to inner-space and Invite you to Enter:<br />THE FRAGLEBAY<br />ON THE KEYBOARD<br />ON THE KEYBOARD<br />on the keyboard<br />on the keyb<br /><br />Stay Fragle!"
  title: "TFB - OTK"
- 
  archive: "https://archive.org/details/BPIST011"
  artist: franky
  coverart: 
    art: "DustAndSoda.jpg"
    thumb: "DustAndSoda.jpg"
  description: "Dust And Soda is radical disco by young Mexican producer, Franky Fresco."
  title: "Dust And Soda"
```

Pretty sure it's me doing something wrong, but i've run out of ways to find it out by myself. Hopefully someone can point me in a good direction.

Thanks for your time,
*Set
