### ISSUE TITLE
 Create pages from all files in a directory

### ISSUE THREAD

**Issue by Jan10** [avillafiorita/jekyll-datapage_gen#52]
Thanks for the create plugin!
Is there a way to create pages from all files in _data folders? 

For example:
```
_data/books/
books.yml
Books-2.yml

_data/shops/
-shop.yml
-xyz.yml
```

**Comment by avillafiorita** [comment]
you just need to populate the ~page_gen~ configuration option with one record per file. 

For instance:

```
page_gen:
  - data: books/books.yml
    template: <<name of the template to use to generate the page for book.yml>>
    name: <<field used to generate the filename>>
    dir: <<directory in which files are to be generated>>
    extension: <<extension used to generate the filename>>
    filter: <<property to filter data records by>>
  - data: books/Books-2.yml
    template: <<name of the template to use to generate the page for book.yml>>
    name: <<field used to generate the filename>>
    dir: <<directory in which files are to be generated>>
    extension: <<extension used to generate the filename>>
    filter: <<property to filter data records by>>
  ...
```
if you  want all pages to land in the same directory, you can try using the same value for ~dir~ in the different entries (**I have not tested it, though**) 

For instance:

```
page_gen:
  - data: books/books.yml
    template: <<name of the template to use to generate the page for book.yml>>
    name: <<field used to generate the filename>>
    dir: books/
    extension: <<extension used to generate the filename>>
    filter: <<property to filter data records by>>
  - data: books/Books-2.yml
    template: <<name of the template to use to generate the page for book.yml>>
    name: <<field used to generate the filename>>
    dir: books/
    extension: <<extension used to generate the filename>>
    filter: <<property to filter data records by>>
  ...
```
Let me know if it solves your issue!

**Comment by Jan10** [comment]
Thanks for your feedback! I explained it in a misleading way, I'm sorry. 
I do not know the total number or names of the files in the folder.

Real world example:
I use the [Jekyll-Contentful-Data-Import](https://github.com/contentful/jekyll-contentful-data-import) to import all the data i create in the contentful backend. 
Now I want to create a page from each .yaml.

![bildschirmfoto 2018-10-12 um 18 13 02](https://user-images.githubusercontent.com/192557/46880984-83446700-ce4a-11e8-98c2-9b487ae9f167.png)

1clkacMDbu6IcOeUES0Ky2.yaml:
```
---
sys:
  id: 1clkacMDbu6IcOeUES0Ky2
  created_at: !ruby/object:DateTime 2018-10-07 16:28:14.617000000 Z
  updated_at: !ruby/object:DateTime 2018-10-07 16:28:14.617000000 Z
  content_type_id: systems
  revision: 1
name: z-wave
```

The result that I would like to have:
`_site/systems/z-wave/index.html`
