### ISSUE TITLE
Request in a remote json file

### ISSUE THREAD

**Issue by marciovsena** [avillafiorita/jekyll-datapage_gen#76]
is it possible to make a request in a remote json file?

```
page_gen-dirs: true
page_gen:
  - data: 'https://run.mocky.io/v3/49577d59-864d-452e-8226-d2abbdf04988'
    template: 'pet'
    name: 'pet_name'
    dir: 'pets'
```
