### ISSUE TITLE
`name_expr` seems to be overriding `title` or `title_expr`

### ISSUE THREAD

**Issue by sahilk** [avillafiorita/jekyll-datapage_gen#79]
`name_expr` seems to be taking precedence for me. Doesn't matter if I use `title` or `title_expr`, `name_expr` is what's being returned for `{{ page.title }}`.

This is what's in my `config.yml`:

```
page_gen:
- data: acts.records
  template: page-act
  dir: acts
  name_expr: record['fields']['act_name'] + "-" + record['id']
  title_expr: record['fields']['act_name']
```

_Originally posted by @sahilk in https://github.com/avillafiorita/jekyll-datapage_gen/issues/72#issuecomment-664029165_
