### ISSUE TITLE
Example of using the paginatehook property?

### ISSUE THREAD

**Issue by iamalfonse** [avillafiorita/jekyll-datapage_gen#80]
So I can see that there is a `paginatehook` property that can be enabled in the options (but not noted in the documentation). I'm just curious if there's a good example of how I'm able to use jekyll's pagination with the datapage-gen.

This is how I tried to set it up locally.

config.yml
```
page_gen:
  - data: blog
    index_files: true
    template: blog-post
    name: slug
    dir: blog
    paginatehook: true

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0                # number of pages. 0 = all
  sort_field: 'date'
  sort_reverse: true
```

_layouts/blog-post
```
---
title: 'Blog'
pagination:
  enabled: true
---

{% for post in paginator.posts %}
<p>{{ post }}</p>
{% endfor %}
```
But it shows me posts found in other _posts directory instead of anything from the data found in the blog data. Any ideas?
