### ISSUE TITLE
variable to get the name of data used to generate pages

### ISSUE THREAD

**Issue by luizeleno** [avillafiorita/jekyll-datapage_gen#87]
Hi,

I wonder if there is a way to use a variable that contains the data used to generate the pages. For instance, in `_config.yml` I have

```yaml
page_gen:

- data: 'EF'
  template: 'course-page'
  name: 'code'
  dir: 'EF'
```

And, in the template file, I would like to access the name of the data used, `'EF'`, like `{{page.data}}` or something like that. Is that implemented?

Thanks!
