### ISSUE TITLE
Documentation: HTML Document Head

### ISSUE THREAD

**Issue by inetbiz** [avillafiorita/jekyll-datapage_gen#96]
I'm running into generating pages because your plug-in fouls out with the `<head>` content in the include file for default layout.

## Default layout
```
---
layout: compress
---
<!DOCTYPE html>
<html lang="{{site.language}}">
   {% include head.html %}
  <body>
  </body>
</html>
```
### Single Layout
```
---
layout: default
---
{% include header.html %}
      <div class="banner">
         <div class="container">
            {% include banner.html %}
         </div>
      </div>
      {% assign product = site.data.products[sku] %}
```

### Output Error
```
(ruby:2.6)[denverpr@pluto furn1]$ bundle exec jekyll build --trace
Configuration file: /home/denverpr/furn1/_config.yml
bundler: failed to load command: jekyll (/home/denverpr/rubyvenv/ruby/2.6/bin/jekyll)
SyntaxError: /home/denverpr/furn1/_plugins/jekyll-datapage-generator.rb:7: syntax error, unexpected '<'
<!DOCTYPE html>
^
/home/denverpr/furn1/_plugins/jekyll-datapage-generator.rb:8: syntax error, unexpected '<'
<html lang="en"
^
/home/denverpr/furn1/_plugins/jekyll-datapage-generator.rb:12: syntax error, unexpected '<'
  <head>
  ^
/home/denverpr/furn1/_plugins/jekyll-datapage-generator.rb:14: syntax error, unexpected '<'
  <link rel="dns-prefetch" href=...
  ^
```

**Comment by avillafiorita** [comment]
Did you downloaded the sources directly from GitHub with "save as"?
In case make sure you choose the "raw" option first, or you might end up with an HTML rather than a ruby file.

Consider also using the gem, which is simpler to install.

Let me know if it solves your issue or we will dig deeper.

**Comment by inetbiz** [comment]
@avillafiorita new error:

```
bundler: failed to load command: jekyll (/home/denverpr/rubyvenv/ruby/2.6/bin/jekyll)
NoMethodError: undefined method `each' for nil:NilClass
  /home/denverpr/furn1/_plugins/jekyll-datapage-generator.rb:180:in `block in generate'
  /home/denverpr/furn1/_plugins/jekyll-datapage-generator.rb:142:in `each'
  /home/denverpr/furn1/_plugins/jekyll-datapage-generator.rb:142:in `generate'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/site.rb:193:in `block in generate'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/site.rb:191:in `each'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/site.rb:191:in `generate'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/site.rb:79:in `process'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /home/denverpr/rubyvenv/ruby/2.6/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
  /home/denverpr/rubyvenv/ruby/2.6/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
  /home/denverpr/rubyvenv/ruby/2.6/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
  /home/denverpr/rubyvenv/ruby/2.6/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
  /home/denverpr/rubyvenv/ruby/2.6/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
  /home/denverpr/rubyvenv/ruby/2.6/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
  /home/denverpr/rubyvenv/ruby/2.6/bin/jekyll:23:in `load'
  /home/denverpr/rubyvenv/ruby/2.6/bin/jekyll:23:in `<top (required)>'
```

**Comment by avillafiorita** [comment]
_config.yml?

**Comment by inetbiz** [comment]
## Config Section
```
# DATA GEN
page_gen-dirs: true

page_gen:
- data: products.study
  template: single
  dir: products/office
  index_files: true
  name: filename
  title: name
  extension: html
```

**Comment by avillafiorita** [comment]
ok, make sure all the required data (products.study, _layouts/single.html) exist.
Make also sure there are a "filename" and a "name" field in your records.
If in doubt, you can add

debug:true 

and run again, it should show what is going on.

**Comment by inetbiz** [comment]
@avillafiorita
`_data/_products/study.yml`
```
sku: 7317
name: Drop Front Desk - Mother of Pearl
description: Fill this IN!
filename: drop-front-desk-mother-pearl
price: 69,550.00
sale_price:
sale_valid: 
cateogry: study
gtin:
isiv4: 
wikidata: 
  - material:
      base: Maple Wood
      plating: Mother of Perl
      Trim: 14k Gold Plating
  - image:
      - name: 7317-main.jpg
        alt: give image description
      - name: 7317-1.jpg
        alt: give image description
      - name: 7317-2.jpg
        alt: give image description
      - name: 7317-3.jpg
        alt: give image description
      - name: 7317-4.jpg
        alt: give image description
      - name: 7317-5.jpg
        alt: give image description
```
![1614792453617](https://user-images.githubusercontent.com/3696477/109846450-38466c80-7c1c-11eb-86c7-c9cdb6cf2adf.png)
