### ISSUE TITLE
Documentation: How to use Jekyll category/tag in generated pages?

### ISSUE THREAD

**Issue by inetbiz** [avillafiorita/jekyll-datapage_gen#97]
I am creating a product site. I need to use category/tag pages built into Jekyll. Ideas?

**Comment by jffrydsr** [comment]
Just dealt with this, try this! (Mind you Page variables like content or title are reserved by Jekyll Layouts object, maybe there should be a _templates dir?) 

#### product.yaml
```yaml 
- id: Soap
  template: template
  data: The best Soap for Ever Lasting Life!
  category: home 
  tags: on-sale, organic
```

#### template.md 
```md
---
title: {{ page.id }}
layout: {{ page.template }}
category: {{ page.category }} 
tags: {{ page.tags }}
---

# {{ page.id }}

> {{ page.data }}

````
_hope this works!_
